# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

test_device="iPhone Xʀ"
iOS_version="12.4"

WORKSPACE="MyProject.xcworkspace"
PROJECT_SCHEME="MyProject"

platform :ios do
  lane :test do
    scan(
      workspace: WORKSPACE,
      device: test_device,
      scheme: PROJECT_SCHEME,
      clean: false,
      code_coverage: true
    )
  end
end