name: Add default label
on: 
  pull_request:
    types: [opened]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@0.8.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          const ready_for_review = "READY FOR REVIEW"
          const issue = { owner: context.issue.owner, repo: context.issue.repo, issue_number: context.issue.number }
          const listLabelsOnIssueResponse = await github.issues.listLabelsOnIssue({...issue})
          const labels = listLabelsOnIssueResponse.data
          if (labels.length == 0) {
            github.issues.addLabels({
              ...issue,
              labels: [ready_for_review]
            })
          }
         
